apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-east1-docker.pkg.dev/noted-extension-333310/dockercoderegistry/bookstore-apache:1.6
        ports:
        - containerPort: 80
