steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
        [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
        docker build -t gcr.io/$PROJECT_ID/frontend:$${VERSION} .
    id: build
    entrypoint: bash

  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
        [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME
        docker push gcr.io/$PROJECT_ID/frontend:$${VERSION}
    id: publish
    entrypoint: bash
    
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          CLUSTER=$$(gcloud config get-value container/cluster)
          PROJECT=$$(gcloud config get-value core/project)
          ZONE=$$(gcloud config get-value compute/zone)
          
          [[ "$BRANCH_NAME" ]] && VERSION=${BRANCH_NAME}-${SHORT_SHA}
          [[ "$TAG_NAME" ]] && VERSION=$TAG_NAME

          gcloud container clusters get-credentials "$${CLUSTER}" \
            --project "$${PROJECT}" \
            --zone "$${ZONE}" 

          NS=qa
          TARGET_ENV=qa 

          #VERSION=$${BRANCH_NAME}-$${VERSION}


          sed -i 's|gcr.io/noted-extension-333310/frontend:.*|gcr.io/noted-extension-333310/frontend:'$${VERSION}'|' ./kubernetes/deployments/$${TARGET_ENV}/*.yaml
          
          kubectl get ns $${NS} || kubectl create ns $${NS}
          kubectl apply --namespace $${NS} -f kubernetes/deployments/$${TARGET_ENV}
