apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deletebook
  labels:
    app: delete-book
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delete-book
  template:
    metadata:
      labels:
        app: delete-book
    spec:
      containers:
      - name: deletebook
        image: gcr.io/noted-extension-333310/deletebook:v10
        ports:
          - containerPort: 8080

        env:
         - name: MYSQL_USERNAME
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username

         - name: MYSQL_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password

         - name: DB_HOST
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbhost
          
        readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
