apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-listbook
  labels:
    app: list-book
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: list-book
  template:
    metadata:
      labels:
        app: list-book
    spec:
      containers:
      - name: listbook
        image: pkarthick83/appinframodwithgke:listbook-latest
        ports:
        - containerPort: 8080

        env:
         - name: MYSQL_USERNAME
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username

         - name: MYSQL_PASSWORD
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password

         - name: DB_HOST
           valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: dbhost
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
